apiVersion: v1
kind: ConfigMap
metadata:
  name: mexy-configv2
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
data:
  index.html: |
    <html>
    <body>
    <h1>Hello World. Version: 2</h1>
    </body>
    </html>